# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fee_calculator_pb2 as fee__calculator__pb2


class FeeCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateFee = channel.unary_unary(
                '/FeeCalculator/CalculateFee',
                request_serializer=fee__calculator__pb2.FeeRequest.SerializeToString,
                response_deserializer=fee__calculator__pb2.FeeResponse.FromString,
                )


class FeeCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateFee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeeCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateFee': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFee,
                    request_deserializer=fee__calculator__pb2.FeeRequest.FromString,
                    response_serializer=fee__calculator__pb2.FeeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FeeCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeeCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FeeCalculator/CalculateFee',
            fee__calculator__pb2.FeeRequest.SerializeToString,
            fee__calculator__pb2.FeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
