# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fee_calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x65\x65_calculator.proto\"=\n\nFeeRequest\x12\x14\n\x0cpackage_size\x18\x01 \x01(\t\x12\x0b\n\x03src\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\x02\"\x1a\n\x0b\x46\x65\x65Response\x12\x0b\n\x03\x66\x65\x65\x18\x01 \x01(\r2:\n\rFeeCalculator\x12)\n\x0c\x43\x61lculateFee\x12\x0b.FeeRequest\x1a\x0c.FeeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fee_calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEEREQUEST._serialized_start=24
  _FEEREQUEST._serialized_end=85
  _FEERESPONSE._serialized_start=87
  _FEERESPONSE._serialized_end=113
  _FEECALCULATOR._serialized_start=115
  _FEECALCULATOR._serialized_end=173
# @@protoc_insertion_point(module_scope)
