openapi: 3.0.3
info:
  title: Fee Calculator API by dPost
  description: A microservice to calculate the gas fee for transporting your package.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: local API
tags:
  - name: Fee Calculator

paths:
  /:
    post:
      operationId: calculate_fee
      summary: calculate fee
      description: Remote procedure to calculate the gas fee for transporting a package.
      tags:
        - Fee Calculator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                  example: 2.0
                method:
                  $ref: "#/components/schemas/method"
                params:
                  type: object
                  properties:
                    package_size:
                      $ref: "#/components/schemas/packageSize"
                    src:
                      type: number
                      example: 0.0
                    dest:
                      type: number
                      example: 1
                  required:
                    - package_size
                    - src
                    - dest
                id:
                  type: string
                  example: 1
              required:
                - jsonrpc
                - method
                - params
                - id
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: integer
                    example: 5
                  error:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: -32602
                      data:
                        type: string
                        example: smal
                      message:
                        type: string
                        example: The package size does not exist.
                      name:
                        type: string
                        example: InvalidParamsError
                    required:
                      - code
                      - data
                      - message
                      - name
                  id:
                    type: string
                    example: 1
                  jsonrpc:
                    type: string
                    example: 2.0
                required:
                  - id
                  - jsonrpc

components:
  schemas:
    method:
      type: string
      enum:
        - calculate_fee
    packageSize:
      type: string
      enum:
        - letter
        - small
        - medium
        - large
